server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
        enabled:true:
        lowerCaseServiceId: true
      routes:
        - id: ratings
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/**
        - id: books
          uri: lb://BOOKSERVICE
          predicates:
            - Path=/books/**
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
